# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'majorBookProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit'
pod 'DropDown', :git => 'https://github.com/snappymob/DropDown.git', :commit => 
  '57027168178b77a9463814fbeb6cda173f301854'
pod 'Then'
pod 'ExpandableCell'
pod 'ExpyTableView'
pod 'Alamofire'  
# Pods for majorBookProject

end
